---
abstract: 'provides zsh completion for OO-Modulinos'
author:
  - 'KOBAYASHI, Hiroaki <hkoba@cpan.org>'
build_requires:
  File::AddInc: '0'
  Test::More: '0.98'
configure_requires:
  Module::Build: '0'
  Module::CPANfile: '0'
dynamic_config: 0
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-oo_modulino_zsh_completion_helper
provides:
  App::oo_modulino_zsh_completion_helper:
    file: lib/App/oo_modulino_zsh_completion_helper.pm
    version: '0.03'
requires:
  MOP4Import::Declare: '0.050'
  Module::Runtime: '0'
  perl: '5.010'
resources:
  repository: https://github.com/hkoba/perl-App-oo_modulino_zsh_completion_helper.git
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
